@startuml
title LifeDuo - Modelo de Dados (ER simplificado)
hide circle
skinparam linetype ortho

entity users {
  *id : uuid <<PK>>
  --
  name : varchar
  email : varchar
  password_hash : varchar
}

entity couples {
  *id : uuid <<PK>>
  --
  streak_current : int
  created_at : timestamp
}

entity checkins {
  *id : uuid <<PK>>
  --
  user_id : uuid <<FK>>
  couple_id : uuid <<FK>>
  mood : varchar
  created_at : timestamp
}

entity goals {
  *id : uuid <<PK>>
  --
  couple_id : uuid <<FK>>
  title : varchar
  progress : int
}

entity gifts {
  *id : uuid <<PK>>
  --
  sender_user_id : uuid <<FK>>
  receiver_user_id : uuid <<FK>>
  provider : varchar
  status : varchar
}

entity pets {
  *id : uuid <<PK>>
  --
  couple_id : uuid <<FK>>
  xp : int
  state : varchar
}

users ||--o{ checkins
couples ||--o{ checkins
couples ||--o{ goals
couples ||--|| pets
users ||--o{ gifts : sender
users ||--o{ gifts : receiver
@enduml
